//! IDL (Interface Definition Language) handling

use crate::error::{Error, Result};
use serde::{Deserialize, Serialize};
use std::fs;
use std::path::Path;

/// Anchor IDL structure
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Idl {
    /// IDL version
    pub version: String,

    /// Program name
    pub name: String,

    /// Instructions
    #[serde(default)]
    pub instructions: Vec<IdlInstruction>,

    /// Accounts
    #[serde(default)]
    pub accounts: Vec<IdlAccount>,

    /// Types
    #[serde(default)]
    pub types: Vec<IdlType>,

    /// Events
    #[serde(default)]
    pub events: Vec<IdlEvent>,

    /// Errors
    #[serde(default)]
    pub errors: Vec<IdlError>,

    /// Metadata
    #[serde(default)]
    pub metadata: IdlMetadata,
}

impl Idl {
    /// Load IDL from file
    pub fn load(path: impl AsRef<Path>) -> Result<Self> {
        let content = fs::read_to_string(path)?;
        let idl: Idl = serde_json::from_str(&content)?;
        Ok(idl)
    }

    /// Save IDL to file
    pub fn save(&self, path: impl AsRef<Path>) -> Result<()> {
        let content = serde_json::to_string_pretty(self)?;
        fs::write(path, content)?;
        Ok(())
    }

    /// Generate TypeScript types from IDL
    pub fn generate_typescript(&self) -> String {
        let mut output = String::new();

        output.push_str(&format!("// Generated by Kawai for {}\n\n", self.name));

        // Generate type definitions
        for ty in &self.types {
            output.push_str(&format!("export interface {} {{\n", ty.name));
            if let Some(fields) = &ty.fields {
                for field in fields {
                    output.push_str(&format!("  {}: {};\n", field.name, self.ts_type(&field.ty)));
                }
            }
            output.push_str("}\n\n");
        }

        // Generate instruction types
        for ix in &self.instructions {
            output.push_str(&format!("export interface {}Args {{\n", to_pascal_case(&ix.name)));
            for arg in &ix.args {
                output.push_str(&format!("  {}: {};\n", arg.name, self.ts_type(&arg.ty)));
            }
            output.push_str("}\n\n");
        }

        output
    }

    /// Convert IDL type to TypeScript type
    fn ts_type(&self, ty: &IdlTypeRef) -> String {
        match ty {
            IdlTypeRef::Simple(s) => match s.as_str() {
                "bool" => "boolean".to_string(),
                "u8" | "u16" | "u32" | "i8" | "i16" | "i32" => "number".to_string(),
                "u64" | "u128" | "i64" | "i128" => "BN".to_string(),
                "publicKey" => "PublicKey".to_string(),
                "string" => "string".to_string(),
                "bytes" => "Buffer".to_string(),
                other => other.to_string(),
            },
            IdlTypeRef::Vec(inner) => format!("{}[]", self.ts_type(inner)),
            IdlTypeRef::Option(inner) => format!("{} | null", self.ts_type(inner)),
            IdlTypeRef::Defined(name) => name.clone(),
            IdlTypeRef::Array { inner, size } => {
                format!("[{}; {}]", self.ts_type(inner), size)
            }
        }
    }
}

/// IDL instruction
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IdlInstruction {
    pub name: String,
    #[serde(default)]
    pub accounts: Vec<IdlAccountRef>,
    #[serde(default)]
    pub args: Vec<IdlArg>,
}

/// IDL account definition
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IdlAccount {
    pub name: String,
    #[serde(rename = "type")]
    pub account_type: IdlAccountType,
}

/// IDL account type
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IdlAccountType {
    pub kind: String,
    #[serde(default)]
    pub fields: Vec<IdlField>,
}

/// IDL account reference in instruction
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IdlAccountRef {
    pub name: String,
    #[serde(rename = "isMut")]
    pub is_mut: bool,
    #[serde(rename = "isSigner")]
    pub is_signer: bool,
}

/// IDL argument
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IdlArg {
    pub name: String,
    #[serde(rename = "type")]
    pub ty: IdlTypeRef,
}

/// IDL field
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IdlField {
    pub name: String,
    #[serde(rename = "type")]
    pub ty: IdlTypeRef,
}

/// IDL type reference
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum IdlTypeRef {
    Simple(String),
    Vec(Box<IdlTypeRef>),
    Option(Box<IdlTypeRef>),
    Defined(String),
    Array {
        #[serde(rename = "array")]
        inner: Box<IdlTypeRef>,
        size: usize,
    },
}

/// IDL type definition
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IdlType {
    pub name: String,
    #[serde(default)]
    pub fields: Option<Vec<IdlField>>,
}

/// IDL event
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IdlEvent {
    pub name: String,
    #[serde(default)]
    pub fields: Vec<IdlField>,
}

/// IDL error
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IdlError {
    pub code: u32,
    pub name: String,
    #[serde(default)]
    pub msg: Option<String>,
}

/// IDL metadata
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct IdlMetadata {
    #[serde(default)]
    pub address: Option<String>,
}

/// Convert snake_case to PascalCase
fn to_pascal_case(s: &str) -> String {
    s.split('_')
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                None => String::new(),
                Some(c) => c.to_uppercase().chain(chars).collect(),
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_pascal_case() {
        assert_eq!(to_pascal_case("hello_world"), "HelloWorld");
        assert_eq!(to_pascal_case("initialize"), "Initialize");
    }
}

